completion_mode = "list"
ctrlc_exit = false
edit_mod = "vi"
header_align = "left"
prompt = "starship_prompt"
startup = [
 "mkdir ~/.cache/starship",
 "starship init nu | save ~/.cache/starship/init.nu",
 "source ~/.cache/starship/init.nu"
]
