#!/bin/sh

# Load profiles from $HOME/.local/etc/profile.d
if test -d $HOME/.local/etc/profile.d/; then
    for profile in $HOME/.local/etc/profile.d/*.sh; do
        test -r "$profile" && . "$profile"
    done
    unset profile
fi

# Load profiles from /opt/local/etc/profile.d
if test -d /opt/local/etc/profile.d/; then
    for profile in /opt/local/etc/profile.d/*.sh; do
        test -r "$profile" && . "$profile"
    done
    unset profile
fi
